grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      class_weight: None
      C: 0.01
      penalty: l2
    search_param_grid:
      C:
      - 0.001
      - 0.01
      - 0.1
      - 1
      - 10
      class_weight:
      - None
      - balanced
      penalty:
      - l1
      - l2

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      n_estimators: 100
    search_param_grid:
      n_estimators:
      - 100
      - 200
      - 300
      criterion:
      - gini
      - entropy