columns:
  LIMIT_BAL: float
  SEX: int
  EDUCATION: int
  MARRIAGE: int
  AGE: int
  PAY_0: int
  PAY_2: int
  PAY_3: int
  PAY_4: int
  PAY_5: int
  PAY_6: int
  BILL_AMT1: float
  BILL_AMT2: float
  BILL_AMT3: float
  BILL_AMT4: float
  BILL_AMT5: float
  BILL_AMT6: float
  PAY_AMT1: float
  PAY_AMT2: float
  PAY_AMT3: float
  PAY_AMT4: float
  PAY_AMT5: float
  PAY_AMT6: float
  default_pay: int

target_column: default_pay

domain_value:
  SEX:
    - 1
    - 2

numerical_columns:
  - LIMIT_BAL
  - SEX
  - EDUCATION
  - MARRIAGE
  - AGE
  - PAY_0
  - PAY_2
  - PAY_3
  - PAY_4
  - PAY_5
  - PAY_6
  - BILL_AMT1
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6